- cmd/cat/cat.go
- cmd/ls/ls.go
- cmd/ls/recordwriter.go
- hack/release/create.sh
- internal/filter/filter.go
- internal/flag/names.go
This also fixes a race conditition in ls
> Add more filters to cat

- cmd/dedup/dedup.go
- internal/filewalker/filewalker.go
> Added more filters to decide which records to deduplicate

- cmd/convert/arc/arc.go
- cmd/convert/nedlib/nedlib.go
- cmd/convert/warc/warc.go
- cmd/dedup/dedup.go
- cmd/dedup/digestindex.go
- cmd/validate/validate.go
- go.mod
- go.sum
- internal/filewalker/filewalker.go
- internal/flag/names.go
- internal/hooks/hooks.go
- internal/hooks/hooks_test.go
- internal/hooks/test_hook.sh
- internal/warcwriterconfig/config.go
Support for hooks to be invoked before and after file reading and file creation
> Processing hooks

- .github/workflows/gh-pages.yml
- hack/doc/serve.sh
- script/completions.sh
This commit makes it easier to understand what
commands are run.
> refactor: use longer argument names

- .golangci.yaml
- internal/cdx.go
- internal/utils/fd_limit_linux.go
> CI: enable `misspell` linter

- .golangci.yaml
- nedlibreader/nedlibreader.go
> CI: enable `bodyclose` linter

- cmd/cat/cat.go
- cmd/cat/cli.go
> Refactor: `cat`

- .github/workflows/main.yml
- internal/config/config_test.go
- internal/filewalker/filewalker_test.go
- internal/hooks/hooks_test.go
> ci: run tests on windows

- .github/workflows/main.yml
- internal/config/config_test.go
> ci: enable mac testing

- .github/workflows/main.yml
- .github/workflows/publish_benchmarks.yml
> ci: enable benchmarking for different OSs

- internal/workerpool/workerpool.go
- internal/workerpool/workerpool_test.go
> refactor: workerpool

- internal/filewalker/filewalker.go
This commit refactors the `filewalker.go` file to
improve the code readability. There are no logical changes.
> refactor: `filewalker.go`

- internal/filewalker/filewalker.go
Having a const variable named `err` is bound to
get confusing, especially when handling errors.
This commit renames the variable from `err` to
`errorLogType`, and also similarly ensures
consistency for the 3 other similar const
variables.
> fix: avoid shadowing err

- cmd/validate/validate.go
This commit refactors the `validate.go` file to
use more descriptive variable names. This makes
the code easier to read and understand.
> refactor: variables in `validate.go`

- internal/ssurt.go
Best reviewed commit by commit.
> refactor: `ssurt.go`

- .github/workflows/gh-pages.yml
- .github/workflows/main.yml
- .github/workflows/publish_benchmarks.yml
- cmd/validate/validate_test.go
The test does panic, but since it is expected it
will not trigger a test failure. Whenever the
validate stops panicking, the test will start
failing.
> test: add initial test for `validate.go`

- cmd/console/RecordWidget.go
- cmd/console/color.go
- cmd/console/console.go
- cmd/console/filter.go
- cmd/console/listwidget.go
- cmd/console/records.go
- cmd/console/shortcuthelpwidget.go
Best reviewed commit by commit. Can squash the commit before merging.
> refactor: `console`

- cmd/convert/arc/arc.go
Best reviewed commit by commit.
> refactor: `arc.go`

- cmd/convert/nedlib/nedlib.go
Best reviewed commit by commit.
> refactor: `nedlib.go`

- cmd/convert/warc/warc.go
Best reviewed commit by commit.
> refactor: `warc.go`

- nedlibreader/nedlibreader.go
This commit renames the variables in
`nedlibreader.go` to make the code more readable.
There are no logic changes.
> refactor: rename variables in `nedlibreader.go`

- internal/filewalker/filewalker.go
- internal/filewalker/helpers.go
- internal/workerpool/workerpool.go
This refactoring will increase readability and
maintainability of the code. There are no
functional changes.
> refactor: split functions in `filewalker.go`

- arcreader/arcreader.go
- arcreader/unmarshaler.go
- cmd/convert/arc/arc.go
- cmd/convert/nedlib/nedlib.go
- cmd/convert/warc/warc.go
- cmd/dedup/dedup.go
- cmd/internal/flag/concurrency_flags.go
- cmd/internal/flag/filter_flags.go
- cmd/internal/flag/hook_flags.go
- cmd/internal/flag/index_flags.go
- cmd/internal/flag/repair_flags.go
- cmd/internal/flag/util_flags.go
- cmd/internal/flag/warcrecordoptions_flags.go
- cmd/internal/flag/warcwriterconfig_flags.go
- cmd/validate/validate.go
This PR fixes some regressions:
- ARC reader closing records too early when wrapped in iterator
- Missing hook variables
- Missing WARC-Info-Record
> Fix ARC reading/writing

- cmd/dedup/dedup.go
- cmd/dedup/dedup_test.go
- internal/warc/iterator.go
- testdata/warc/dedup.warc
> Fix deduplication of revisit record will cause panic
