main_test.go

A very simple test that ensures the CLI tool responds correctly to zero input.
A followup commit should enable testing in the CI.

Create tiny top level test

---

.github/dependabot.yaml

To avoid having to manually update dependencies,
we can use `Dependabot` to automatically create
pull requests when new versions of dependencies
are available.
The config file added in this commit enables
`Dependabot` to manage the dependencies for `go`,
`Github-actions` and `docker`.

ci: add `dependabot` configuration

---

.github/workflows/gh-pages.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

This commit reduces the clutter when viewing pull
requests, as we have less builds to look at.
When triggers for both `push` and `pull_request`
are defined, the `pull_request` trigger is
redundant and can be removed.

ci: remove unnecessary `GitHub Actions` triggers

---

.goreleaser.yml

This commit changes the name and email of the
maintainer, in order to avoid external
communications is lost.

docs: change maintainer

---

docs/content/contributing/_index.md

The required version of `go` is now 1.21. This was found by running `go test ./...` and getting the
following error message:
```
internal/hooks/hooks_test.go:23:2: package slices
is not in GOROOT (/usr/local/go/src/slices)
note: imported by a module that requires go 1.21
FAIL	github.com/nlnwa/warchaeology/internal/
hooks [setup failed]
```

docs: update required version of `go`

---

.golangci.yaml

A lot of sub-linters are disabled by default when
using `golangci-lint`. This commit now makes it
explicit which sub-linters are used and which ones are not.
All of the sub-linters that failed have been
disabled.
Introduces
https://github.com/nlnwa/warchaeology/issues/66

ci: configure `golangci-lint`

---

.golangci.yaml

This commit ensures that imports are consistently
formatted across the project.
All files were previously formatted with
`goimports`, in commit
6f6b515193623671dc75a398c867f9d8aa810877.

ci: enable `goimports` linter

---

cmd/aart/aart.go
cmd/cat/cat.go
cmd/console/console.go
cmd/convert/arc/arc.go
cmd/convert/nedlib/nedlib.go
cmd/convert/warc/warc.go
cmd/dedup/dedup.go
cmd/ls/ls.go
cmd/validate/validate.go

To increase readability and testability,
separating the command line arguments from the
business logic is a good idea.
As a step in this direction, this commit creates
new functions for handling the arguments, even if
all argument handling is not done in these
functions just yet.
Follow up commits will further make this
separation clearer.

refactor: separation of arguments and logic

---

.github/workflows/release.yml

The following error inspired this commit:
```
• DEPRECATED: --rm-dist was deprecated in favor of
--clean, check
https://goreleaser.com/deprecations#-rm-dist for
more details
```
The actual fix was simply doing as the error
message suggested.

fix: replace deprecated `goreleaser` command

---

.github/workflows/main.yml

To be able to build and release more automatic and less dependent on the local environment, we need
to store the build artifacts in a place where we
can access them later.
Stores some of the build artifacts from the `dist` directory after a successful build.
Use these artifacts to create a release together
with autogenerated docs.
Ideally the artifacts should be built in a
separate job to avoid potential contamination of
the build environment. But because this is a paid
`gorelease` feature we will just have to continue
building all targets in one go.

ci: store artifacts after build

---

.goreleaser.yml

This commit solves the following warning which is
blocking us from upgrading `goreleaser` to a newer version:
```
• DEPRECATED: `nfpms.replacements` should not be
used anymore, check
https://goreleaser.com/deprecations#nfpmsreplacements
for more info
```
The fix was simply to remove it, it seems like it
was relevant in commit
b765ea8657fba82ab8cdc69bf4d7bbe4ad812863 when it
was used for changing the file name. But it became dead code after commit
358436f354446a34495158698ca85b65057d6500
If we truly want to support the distributions that we provide artifacts for, we need automatic
testing.

fix: remove deprecated `replacements`

---

.github/workflows/main.yml

This commit bumps the `goreleaser` version to
`1.24.0` from version `1.18.2`.

build: bump `goreleaser` version

---

main_test.go

This commit fixes the issue where running `go
test` would write to stdout. This was caused by
commit 0c94a34011af2c7135fbae6598abc8790e087a25.
The solution is just to redirect `stdout` and
`stderr` to `nil`.
Solves https://github.com/nlnwa/warchaeology/issues/87

fix: silence output when running `go test`

---

.github/workflows/main.yml
.github/workflows/publish_benchmarks.yml
cmd/cat/cat_test.go

CI: add benchmark workflow

---

.github/workflows/publish_benchmarks.yml

The current benchmarking system does not compare
the results with previous benchmarks, as we have
no place to store the results.
This commit ensures that this is no longer the
case by pushing the benchmark results to a
dedicated branch called `benchmark-results`.
After pushing the benchmark results to `GitHub
pages`, a json is now created and automatically
committed to the `benchmark-results` branch.
Use `actions/cache` to store the results. The
reason why this was not done is that the entries
in the cache will expire after a set amount of
time, which is likely to happen. In such a
scenario there will be additional burdens on the
developers to manually update the cache.
The benchmark results had to be moved out of the
working directory because of conflicts with the
checkout actions.

ci: push benchmark results to dedicated branch

---

.github/workflows/main.yml

The previous commits of
343fb0a3b0d48856cb1af9237c43d0601f728a63 and
8f539bf9177c182a8d600cea02076538fc95a048 added
creation and storage of benchmark results.
This commit now does the final stage which is to
compare the new benchmark results with the
previous results.
Renamed the benchmark name to `Go Benchmark` so
that it matches the benchmark name uploaded by
`publish_benchmarks.yml`, otherwise the comparison will never work.
Use download previous benchmarks from the
dedicated `benchmark-results` branch.

ci: compare with previous benchmarks

---

.github/workflows/main.yml
.github/workflows/publish_benchmarks.yml

This reverts commit 99cda7ca342e449875e6b44db08292a0264eb5f9.
The reason for this revert is that publishing the
benchmark results failed with the following error:
```
Run mkdir --parents benchmarks/macos-13/
mkdir --parents benchmarks/macos-13/
shell: /bin/bash -e {0}
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
Process completed with exit code 64.
```

Revert "ci: enable benchmarking for MacOS"

---

.github/workflows/main.yml
.github/workflows/publish_benchmarks.yml

This reverts commit 4356a8f0d0148835b87cd8463f2b8e9b82a078a5.
The reason for this revert is that publishing the
benchmark results failed with the following error:
```
mkdir: D:\a\_temp\7b514a37-675e-4b59-90db-e2c0e048869e.ps1:2
Line |
2 |  mkdir --parents benchmarks/windows-2022/
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| A positional parameter cannot be found that
accepts argument 'benchmarks/windows-2022/'.
Error: Process completed with exit code 1.
```

Revert "ci: enable benchmarking for windows"

---

internal/filewalker/filewalker.go
internal/filewalker/filewalker_test.go

fix: handle filewalker errors

---

.gitattributes
cmd/ls/ls_test.go
test-data/samsung-with-error/README.md
test-data/samsung-with-error/rec-33318048d933-20240317162652059-0.warc.gz

Many top level commands are missing tests. This is a first step to add a test for `ls` with proper
test data.
This commit adds a very simple test for `ls` that
checks that it does not crash when reading a file.
Add more checks to the test so that it is even
better at avoiding regressions.
Thanks to Ilya Kreymer for providing the test data through issue
https://github.com/nlnwa/warchaeology/issues/99

test: add simplest test for `ls`

---

cmd/ls/ls_test.go

To reduce the risk of performance regressions, we
should have a benchmark for `ls`.

test: initial benchmark for `ls`

---

cmd/ls/ls.go
cmd/ls/recordwriter.go

fix: error handling for `ls.RecordWriter`

---

.github/workflows/main.yml
.github/workflows/publish_benchmarks.yml
continuous-integration/check_push_status.py
continuous-integration/create_dir.py

This commit is not quite a revert of commit
a91ef1303089616d253cd508783f429e3d2a85d9, but it
is close. The main difference is that this commit
handles the creation of the directories and
verification of the `push` status in an OS
agnostic way.
To avoid race conditions, each of the benchmark
jobs are now running one at a time, otherwise
there might be upload collision.

ci: enable windows benchmarks

---

go.mod
internal/workerpool/workerpool_test.go

This commit adds a test that checks for goroutine
leaks in the `workerpool` package, and also fixes
two goroutine leaks.
There is unfortunately no easy way of running
`goleak` before every test without either a lot of copy-paste, or additional code to ensure every
test file has a `TestMain` function.
A leaked goroutine will produce the following
error with `goleak`:
```
goleak: Errors on successful test run: found
unexpected goroutines: [Goroutine 7 in state chan
receive, with
github.com/nlnwa/warchaeology/internal/workerpool
.New.func1 on top of the stack: goroutine 7 [chan
receive]:
github.com/nlnwa/warchaeology/internal/workerpool.
New.func1(0xc00008a1e0)
./warchaeology/internal/workerpool/workerpool.go:
23
+0x66 created by
github.com/nlnwa/warchaeology/internal/workerpool.New
in …
```

test: avoid leaking goroutines

---

cmd/ls/ls_test.go

Since commit
d8d316a6707a8f3e2234e5c483250ab7b99943de the
benchmark results of `BenchmarkReadFileWithError`
are no longer present.
`BenchmarkReadFileWithError` has not been deleted, and it seems like some of the output printed to
the benchmark result file causes
`github-action-benchmark` to fail finding this
result.
The reason why commit
d8d316a6707a8f3e2234e5c483250ab7b99943de triggered this error is because it added the required `lfs`
checkout so that the test-data was cloned
correctly.
As a workaround, this commit silences the output
of the benchmark `BenchmarkReadFileWithError`.

fix: silence benchmark output

---

cmd/convert/nedlib/nedlib.go

This commit refactors part of `nedlib.go` to make
it easier to read. The code was tested manually to ensure that `covert nedlib` still works as
expected, but no automated tests were added.

refactor: `nedlib.go` function

---

.gitattributes
cmd/convert/nedlib/nedlib_test.go
test-data/nedlib/nb-image/b863a630196bce1a15ca86b40f34a2d5
test-data/nedlib/nb-image/b863a630196bce1a15ca86b40f34a2d5.meta
test-data/nedlib/nb-image/e4a2d28bdf4c38b8f6f291f7c8c958d5
test-data/nedlib/nb-image/e4a2d28bdf4c38b8f6f291f7c8c958d5.meta

This commit adds initial test data for the
`nedlib` format. The test data was provided by the National Library of Norway.
A minimal test was added to use this test data.

test: add initial test data for `nedlib`

---

.github/workflows/gh-pages.yml

The latest version of `hugo` breaks the building
of the documentation with the following error:
```
ERROR render of "taxonomy" failed:
"/home/runner/work/warchaeology/warchaeology/docs/themes/ace-documentation/layouts/_default/baseof.html:3:8":
execute of template failed: template:
_default/list.html:3:8: executing
"_default/list.html" at <partial "head.html" .>:
error calling partial: execute of template failed:
html/template:partials/head.html:29:20: no such
template "_internal/google_analytics_async.html"
ERROR render of "section" failed:
"/home/runner/work/warchaeology/warchaeology/docs/themes/ace-documentation/layouts/_default/baseof.html:3:8":
execute of template failed: template:
_default/list.html:3:8: executing
"_default/list.html" at <partial "head.html" .>:
error calling …
```

fix: set `hugo` version to `1.24.1`

---

nedlibreader/nedlibreader.go
nedlibreader/time.go
nedlibreader/time_test.go

`nedlib` data might contain a lot of different
time formats. This commit adds a function to parse the time format used in `nedlib` data.
Add parsing of custom time formats.

fix: parse time function for `nedlib`

---

.gitattributes
cmd/cat/cat.go
cmd/cat/cat_test.go
cmd/cat/cli.go
internal/warc/iterator.go
internal/warc/iterator_test.go
testdata/single-record.warc

The [gowarc.WarcFileReader](https://pkg.go.dev/github.com/nlnwa/gowarc#WarcFileReader) does not provide a simple way to get the size of the next record.
This PR introduces an iterator abstraction for iterating over WARC records. In addition to returning the size of each record the iterator encapsulates:
- filtering records
- limiting the number of records
- selecting the nth record
~This PR only includes the implementation of the iterator. Future pull requests will start using it.~
edit: added use cases

feat: WARC record iterator

---

nedlibreader/time.go
nedlibreader/time_test.go

This PR adds special handling of a specific occurence of RFC1123 timestamp  with broken year.

fix: parse broken rfc1123 format
